### PR TITLE
Added total price of unique orders and changed...

### PR DESCRIPTION
**Pull request by mifunetoshiro**
n_unique_orders to int

### CODE REVIEW

**Comment by mifunetoshiro** [comment]
Hm, although this rounding to 2 decimals isn't that great for the ETH-BTC pair (e.g. 1 ETH for 0.08701 BTC by 1 unique order gets rounded to 0.09 BTC)...

**Comment by theimo1221** [comment]
You should seperate calculation of that line and add detection of significant decimals

**Comment by theimo1221** [comment]
You can use my rounding algorithm of #34

**Comment by pmaji** [comment]
Will look into this one shortly.

**Comment by pmaji** [comment]
@mifunetoshiro there have been a lot of changes between now and this version. I still like this idea, but go ahead and update your commit to master and see if integrating @theimo1221's algorithm for rounding will accomplish what you wanted. Once you test it locally I'll merge it to master :)

**Comment by mifunetoshiro** [comment]
Actually this rounding thing is a non-issue when it comes to "whales," this was just a minor difference I noticed when comparing small "fish" 1 ETH-BTC orders, which aren't even shown on the graph. I don't think it matters whatsoever if for example, 501.99 ETH for 0.083 BTC total price gets rounded from 41.66517 to 41.67 BTC, agree? There is also no need to use theimo1221's algorithm, round(2) is adequate and there is no need to complicate things.

By the way, there is a typo in the repository name, "whatching" instead of "watching."

**Comment by mifunetoshiro** [comment]
It'd also be great if hovering over a "ladder" would produce the same tooltip as when you hover over a bubble, including the total price of all the stacked orders in the ladder.

**Comment by theimo1221** [comment]
@mifunetoshiro The "ladder" is a "line" in plotly and doesn´t support the tootip.....

That´s why I was forced to do this workaround with putting annotations on the top/bot position of each line......
Even for code it would be a good bonus to just use tooltip, but as I said, if I could I would

**Comment by mifunetoshiro** [comment]
How about something like https://stackoverflow.com/a/46039229

**Comment by theimo1221** [comment]
Open a new issue on it please

**Comment by pmaji** [comment]
Yep. I think I'm comfortable with all the rounding presently. If it comes back up in edge cases I didn't think of, we can cover it then on an ad-hoc basis, but I'm going to close this issue.

**Pull request closed without merging**
