### PR TITLE
Color the bg above market red, below market green

### PR DESCRIPTION
**Pull request by mifunetoshiro**
For #44:

bgcolor

### CODE REVIEW

**Comment by theimo1221** [comment]
Nice workaround but it´ll be problematic for later unique color changing cause i can´t separate those 2 huge shapes from the ladders....

**Comment by pmaji** [comment]
@theimo1221 can you clarify what you mean by later unique color changing? You mean future JS improvements to overall aesthetic?

**Comment by theimo1221** [comment]
@pmaji and @mifunetoshiro 
Yes I mean the JS improvements.
If we change it like merged here JS won´t have the possibility to change background color.
I mean JS can change color behind that shapes but it couldn´t change the shapes, without changing all laders.

**Comment by mifunetoshiro** [comment]
Just remove these 10 lines when the JS changes are ready. But I really don't think the unique colouring option is necessary as I said in #44. Cryptowatch and exchanges don't offer you to choose colours either (except change theme maybe), and even if they did, not many would change them. Personally I think red/green is perfect and most fitting, the same as on all exchanges...

**Pull request merged**
