### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by mifunetoshiro**
Replaces current #60 pull request

### CODE REVIEW

**Comment by mifunetoshiro** [comment]
By the way, is there any particular reason why the run_server host IP is 0.0.0.0 and not 127.0.0.1? Do I change it back?

**Comment by theimo1221** [comment]
[https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost](That´s why we use 0.0.0.0)

**Comment by mifunetoshiro** [comment]
Ok, changed back to 0.0.0.0. Was just confusing to me because the app said it was running on 0.0.0.0, which I couldn't connect to.

**Comment by theimo1221** [comment]
Yes, for your PC it is running on 0.0.0.0 but to connect to it usually you need to visit [http://localhost:8050](http://localhost:8050) or [http://localhost:8050](http://localhost:8050)

Thnaks for your changes

**Pull request merged**
